echo "Adding repositories..."
sudo add-apt-repository -y ppa:chris-lea/node.js > /dev/null 2>&1
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo Updating APT-GET...
sudo apt-get update -qq
echo Installing curl...
sudo apt-get install -qqy curl
echo Installing dkms...
sudo apt-get install -qqy dkms
echo Installing git...
sudo apt-get install -qqy git
echo Installing nodejs...
sudo apt-get install -qqy nodejs
echo Installing pip...
sudo apt-get install -qqy python-dev python-pip
echo Installing ruby...
sudo apt-get install -qqy ruby1.9.1
echo Installing xclip...
sudo apt-get install -qqy xclip
echo Installing zsh...
sudo apt-get install -qqy zsh
echo Installing dev libraries...
sudo apt-get install -qqy libffi-dev
sudo apt-get install -qqy libssl-dev
sudo apt-get install -qqy libxml2-dev
sudo apt-get install -qqy libxslt1-dev
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
pip install virtualenv --user
pip install virtualenvwrapper --user
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
if [ ! -d ~/.oh-my-zsh ]; then
  echo Installing oh-my-zsh...
  curl -sL https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | bash
fi
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo Cleaning...
sudo apt-get autoremove -qqy
